# Generated by Django 3.2 on 2021-05-03 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=64)),
                ('atype', models.IntegerField()),
                ('profile_picture', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-aid'],
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('house_number', models.CharField(max_length=25)),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cereal.accountmodel')),
            ],
            options={
                'ordering': ['-cid'],
            },
        ),
        migrations.CreateModel(
            name='LocationsModel',
            fields=[
                ('zipcode', models.IntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-country', '-zipcode'],
            },
        ),
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfilePictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartModel',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cereal.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('oID', models.AutoField(primary_key=True, serialize=False)),
                ('paymentStatus', models.BooleanField()),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cereal.customermodel')),
                ('SCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal.shoppingcartmodel')),
            ],
            options={
                'ordering': ['-oID'],
            },
        ),
        migrations.AddField(
            model_name='customermodel',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cereal.locationsmodel'),
        ),
        migrations.CreateModel(
            name='CartContentsModel',
            fields=[
                ('scid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cereal.shoppingcartmodel')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cereal.productmodel')),
            ],
        ),
    ]
