# Generated by Django 3.2 on 2021-05-05 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0002_auto_20210504_1539'),
    ]

    operations = [
    ]
