# Generated by Django 3.2 on 2021-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0003_auto_20210505_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='description',
            field=models.CharField(default='', max_length=2500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
