# Generated by Django 3.2 on 2021-05-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0004_auto_20210505_0916'),
    ]

    operations = [

    ]
