# Generated by Django 3.2 on 2021-05-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0010_remove_productmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartmodel',
            name='CID',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='SCID',
        ),
        migrations.DeleteModel(
            name='ShoppingCartModel',
        ),
    ]
