# Generated by Django 3.2 on 2021-05-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210504_1548'),
        ('cereal', '0011_auto_20210505_0953'),
    ]

    operations = [
    ]
