# Generated by Django 3.2 on 2021-05-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0012_auto_20210505_0956'),
    ]

    operations = [
    ]
