# Generated by Django 3.2 on 2021-05-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0014_auto_20210505_1038'),
    ]

    operations = [
]
