# Generated by Django 3.2 on 2021-05-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0002_candycategory'),
        ('cereal', '0016_ordermodel'),
    ]

    operations = [
    ]
