# Generated by Django 3.2 on 2021-05-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0017_merge_0002_candycategory_0016_ordermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImageModel',
        ),
    ]
