# Generated by Django 3.2 on 2021-05-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0018_auto_20210505_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cereal.productmodel')),
                ('image', models.ImageField(upload_to='images/products')),
                ('default', models.BooleanField(default=False)),
            ],
        ),
    ]
