# Generated by Django 3.2 on 2021-05-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0020_rename_cid_shoppingcartmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
