# Generated by Django 3.2 on 2021-05-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0021_auto_20210505_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='', upload_to='products/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductImageModel',
        ),
    ]
