# Generated by Django 3.2 on 2021-05-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0022_auto_20210505_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='stock',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
