# Generated by Django 3.2 on 2021-05-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210505_1554'),
        ('cereal', '0024_auto_20210505_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCartModel',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.ManyToManyField(to='cereal.ProductModel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='SCID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cereal.shoppingcartmodel'),
            preserve_default=False,
        ),
    ]
