# Generated by Django 3.2 on 2021-05-05 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0025_auto_20210505_1554'),
    ]

    operations = [
    ]
