# Generated by Django 3.2 on 2021-05-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0026_rename_user_id_shoppingcartmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='SCID',
        ),
        migrations.DeleteModel(
            name='ShoppingCartModel',
        ),
    ]
