# Generated by Django 3.2 on 2021-05-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0028_auto_20210505_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='pid',
            new_name='id',
        ),

    ]
