# Generated by Django 3.2 on 2021-05-05 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0009_auto_20210505_1554'),
        ('cereal', '0030_auto_20210505_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2500)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartModel',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.ManyToManyField(to='cereal.ProductModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('pid', models.ManyToManyField(to='cereal.ProductModel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('oID', models.AutoField(primary_key=True, serialize=False)),
                ('paymentStatus', models.BooleanField()),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
                ('SCID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cereal.shoppingcartmodel')),
            ],
            options={
                'ordering': ['-oID'],
            },
        ),
    ]
