# Generated by Django 3.2 on 2021-05-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0033_auto_20210506_1503'),
    ]

    operations = [

    ]
