# Generated by Django 3.2 on 2021-05-12 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cereal', '0034_productmodel_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='paymentStatus',
            field=models.BooleanField(default=False),
        ),
    ]
