# Generated by Django 3.2 on 2021-05-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0035_auto_20210512_1552'),
    ]

    operations = [
    ]
