# Generated by Django 3.2 on 2021-05-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0037_order_orderitem'),
    ]

    operations = [
    ]
