# Generated by Django 3.2 on 2021-05-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0038_auto_20210512_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='cereal.OrderItem'),
        ),
    ]
