# Generated by Django 3.2 on 2021-05-12 18:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cereal', '0039_auto_20210512_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'toaeu': 'aeou'}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
