# Generated by Django 3.2 on 2021-05-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_merge_0031_alter_profile_zipcode_0035_profile_zipcode'),
        ('cereal', '0041_auto_20210512_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
