# Generated by Django 3.2 on 2021-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210505_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_cvc',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_expiration',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_holder',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
