# Generated by Django 3.2 on 2021-05-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=0, upload_to='static/images/users'),
            preserve_default=False,
        ),
    ]
