# Generated by Django 3.2 on 2021-05-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_profile_card_expiration'),
        ('user', '0013_alter_profile_profile_image'),
    ]

    operations = [
    ]
