# Generated by Django 3.2 on 2021-05-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_merge_20210511_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='searches',
            field=models.ManyToManyField(to='user.SearchHistory'),
        ),
    ]
