# Generated by Django 3.2 on 2021-05-11 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210511_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='searches',
            field=models.ManyToManyField(null=True, to='user.SearchHistory'),
        ),
    ]
