# Generated by Django 3.2 on 2021-05-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210511_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='searches',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
