# Generated by Django 3.2 on 2021-05-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210511_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searches',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile'),
        ),
    ]
