# Generated by Django 3.2 on 2021-05-11 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20210511_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searches',
            name='url',
        ),
        migrations.AddField(
            model_name='searches',
            name='query',
            field=models.CharField(default='0', max_length=999999),
            preserve_default=False,
        ),
    ]
