# Generated by Django 3.2 on 2021-05-11 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210511_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searches',
            name='token',
        ),
    ]
