# Generated by Django 3.2 on 2021-05-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20210512_1156'),
    ]
    operations = [
    ]
