# Generated by Django 3.2 on 2021-05-12 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_profile_location_id'),
    ]

    operations = [
    ]
