# Generated by Django 3.2 on 2021-05-12 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20210512_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationsModel',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-country'],
            },
        ),
    ]
