# Generated by Django 3.2 on 2021-05-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20210512_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='user.locationsmodel'),
        ),
    ]
