# Generated by Django 3.2 on 2021-05-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_remove_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Funky Town', max_length=255),
            preserve_default=False,
        ),
    ]
