# Generated by Django 3.2 on 2021-05-12 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_profile_card_cvc'),
        ('user', '0029_profile_city'),
    ]

    operations = [
    ]
