# Generated by Django 3.2 on 2021-05-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_merge_0024_alter_profile_card_cvc_0029_profile_city'),
    ]

    operations = [
    ]
