# Generated by Django 3.2 on 2021-05-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_merge_0024_alter_profile_card_cvc_0029_profile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
