# Generated by Django 3.2 on 2021-05-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_profile_zipcode'),
    ]

    operations = [

    ]
