# Generated by Django 3.2 on 2021-05-12 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20210512_1258'),
    ]

    operations = [
    ]
