# Generated by Django 3.2 on 2021-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_remove_profile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
