# Generated by Django 3.2 on 2021-05-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_profile_zipcode'),
        ('user', '0035_profile_zipcode'),
    ]

    operations = [
    ]
